- name: Clone respeaker driver into {{ respeaker_driver_dir }}
  ansible.builtin.git:
    repo: "{{ respeaker_driver_repo }}"
    dest: "{{ respeaker_driver_dir }}"
    version: "{{ respeaker_driver_version }}"
    force: true
    update: true

- name: Run installer version {{ respeaker_driver_version }}
  changed_when: true
  check_mode: false
  ansible.builtin.command:
    cmd: "{{ respeaker_driver_dir }}/install.sh"
    chdir: "{{ respeaker_driver_dir }}"
  register: respeaker_driver_install
  failed_when:
    - 'respeaker_driver_install.rc != 0 and "Please reboot your raspberry pi to apply all settings" not in respeaker_driver_install.stdout'

- name: Reboot
  ansible.builtin.reboot:
