- name: Clone wyoming-openwakeworkd into {{ respeaker_wyoming_openwakeword_dir }}
  ansible.builtin.git:
    repo: "{{ respeaker_wyoming_openwakeword_url }}"
    dest: "{{ respeaker_wyoming_openwakeword_dir }}"
    version: "{{ respeaker_wyoming_openwakeword_version }}"
    force: true
    update: true

- name: Check service if it is running
  block:
    - name: Get service file
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ respeaker_wyoming_openwakeword_name }}.service"
      register: respeaker_wyoming_openwakeword_service_file

    - name: Stop service
      when: respeaker_wyoming_openwakeword_service_file.stat.exists
      ansible.builtin.systemd:
        name: "{{ respeaker_wyoming_openwakeword_name }}"
        state: stopped

- name: Run installer {{ respeaker_wyoming_openwakeword_name }}
  changed_when: true
  check_mode: false
  ansible.builtin.command:
    cmd: "{{ respeaker_wyoming_openwakeword_dir }}/script/setup"
    chdir: "{{ respeaker_wyoming_openwakeword_dir }}"
  register: wyoming_satellite_localwakework_install

- name: Apply fix https://github.com/rhasspy/wyoming-satellite/issues/157
  ansible.builtin.pip:
    name: "numpy<2"
    chdir: "{{ respeaker_wyoming_openwakeword_dir }}"
    virtualenv: "{{ respeaker_wyoming_openwakeword_dir }}/.venv"

- name: Show installer output
  ansible.builtin.debug:
    msg: "{{ wyoming_satellite_localwakework_install }}"
    verbosity: 1
  #  failed_when:
#    - 'wyoming_satellite_install.rc != 0 and "DKMS tree already contains: seeed-voicecard-0.3" not in wyoming_satellite_install.stderr'
- name: Create service file
  ansible.builtin.template:
    src: "{{ respeaker_wyoming_openwakeword_name }}.service.j2"
    dest: "/etc/systemd/system/{{ respeaker_wyoming_openwakeword_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart {{ respeaker_wyoming_openwakeword_name }}

- name: Start wyoming-openwakeword
  ansible.builtin.service:
    name: "{{ respeaker_wyoming_openwakeword_name }}"
    state: started
    enabled: true
    daemon_reload: true
  notify: Restart {{ respeaker_wyoming_openwakeword_name }}
